import Link from 'next/link';
import {absoluteUrl,buildMetadata,solutionSeo} from '@/lib/seo';
import StructuredData from '@/components/StructuredData';

const seo=solutionSeo.production;
export const metadata=buildMetadata({...seo,path:'/solutions/production'});

export default function Page(){
 const schema={'@context':'https://schema.org','@type':'Service',name:seo.title,description:seo.description,url:absoluteUrl('/solutions/production'),areaServed:[{'@type':'City',name:'Москва'},{'@type':'AdministrativeArea',name:'Московская область'}],provider:{'@type':'Organization',name:'ООО «Промбезопасность Консалт»',url:absoluteUrl('/')}};
 return <main><StructuredData data={schema}/><section className="innerHero"><div className="wrap breadcrumbs"><Link href="/">Главная</Link> / <Link href="/solutions">Решения</Link> / Производство</div><div className="wrap serviceHero"><div><span className="kicker">Решение для отрасли</span><h1>Охрана труда для производственных компаний Москвы и МО.</h1><p className="lead">Страница строится вокруг специфики предприятия – рабочих мест, опасностей, оборудования, обучения и контроля процессов.</p><div className="actions"><Link className="primaryButton" href="/calculator">Оценить объём работ</Link><a className="secondaryButton" href="#specifics">Что учитывать</a></div></div><div className="photoPlaceholder compact serviceFactCard"><b>Производство</b><span>Москва и Московская область</span><span>Состав работ – после первичного аудита предприятия</span></div></div></section><section className="section white" id="specifics"><div className="wrap"><div className="splitHead"><div><span className="kicker">Специфика</span><h2>Что делает производство отдельным сценарием.</h2></div><p>Состав работ определяется по фактическим процессам предприятия, рабочим местам и выполняемым операциям.</p></div><div className="cardGrid three"><div className="plainCard tall"><h3>Рабочие места и опасности</h3><p>Нужно учитывать реальный характер производственных операций.</p></div><div className="plainCard tall"><h3>Обучение и допуски</h3><p>Набор обязательных мероприятий зависит от выполняемых работ.</p></div><div className="plainCard tall"><h3>Документация и процессы</h3><p>Система должна отражать фактическую структуру предприятия.</p></div></div></div></section><section className="section soft"><div className="wrap"><div className="splitHead"><div><span className="kicker">Путь клиента</span><h2>От отрасли – к конкретной задаче.</h2></div><p>Посетитель выбирает то, что происходит в его компании.</p></div><div className="cardGrid three"><Link className="plainCard clickable" href="/services/outsourcing-ohrany-truda"><h3>Нужно сопровождение целиком</h3><b>Аутсорсинг →</b></Link><Link className="plainCard clickable" href="/services/professional-risks"><h3>Нужна оценка рисков</h3><b>Подробнее →</b></Link><Link className="plainCard clickable" href="/resources/git-checklist"><h3>Предстоит проверка</h3><b>Начать с чек-листа →</b></Link></div><div className="actions" style={{marginTop:28}}><Link className="textLink" href="/knowledge/ocenka-professionalnyh-riskov">Как организовать оценку профессиональных рисков →</Link></div></div></section><section className="section white"><div className="wrap pricePanel"><span className="kicker light">Предварительная оценка</span><h2>Не знаете, какие работы нужны вашему производству?</h2><p>Калькулятор задаст пять вопросов и поможет предварительно определить, какие блоки стоит проверить. Точная стоимость формируется после аудита.</p><Link className="inverseButton" href="/calculator">Перейти к калькулятору</Link></div></section></main>}
